apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-baxl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-baxl
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-baxl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-baxl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-baxl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rels-tenant/status-quarkus-io/statusquarkusio-baxl@sha256:0c2bb81bd6f083e6effcf40648d9c918f3f4e9fe6b5ff5354bddfdbfaaf78948
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
